### ISSUE TITLE
About the DiffAE pre-trained model 

### ISSUE THREAD

**Issue by ZHANG-YSen** [hansam95/OSASIS#3]
I'm sorry to disturb you. Because I am very interested in your work and am trying to reproduce the code of this paper.

But I can't download the DiffAE pre-trained model trained on FFHQ ( [ffhq256_autoenc], [ffhq256_autoenc_latent] ).

Can you upload these two files ([ffhq256_autoenc], [ffhq256_autoenc_latent]) in Google drive or send to my email (1484089750@qq.com). 

Thank you very much!

**Comment by hansam95** [comment]
I apologize for the delayed response. I've fixed the links for the DiffAE pre-trained models. You should now be able to download the models, as mentioned in the guidelines.

Please let me know if you encounter any further issues.
Thank you!
